# frozen_string_literal: true

# ============================================================================
# Summary Statistics
# ============================================================================

puts "\n✅ Seeding complete!"
puts "\nCreated:"
puts "  - #{PromptTracker::Prompt.count} prompts"
puts "  - #{PromptTracker::PromptVersion.count} prompt versions"
puts "    - #{PromptTracker::PromptVersion.active.count} active"
puts "    - #{PromptTracker::PromptVersion.draft.count} draft"
puts "    - #{PromptTracker::PromptVersion.deprecated.count} deprecated"
puts "  - #{PromptTracker::Test.count} tests"
puts "    - #{PromptTracker::Test.where(testable_type: 'PromptTracker::PromptVersion').count} for prompts"
puts "    - #{PromptTracker::Test.where(enabled: true).count} enabled"
puts "  - #{PromptTracker::Dataset.count} datasets"
puts "    - #{PromptTracker::DatasetRow.count} dataset rows"
puts "  - #{PromptTracker::LlmResponse.count} LLM responses"
puts "    - #{PromptTracker::LlmResponse.successful.count} successful"
puts "    - #{PromptTracker::LlmResponse.failed.count} failed"
puts "  - #{PromptTracker::Evaluation.count} evaluations"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%LlmJudgeEvaluator").count} LLM judge"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%KeywordEvaluator").count} keyword"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%LengthEvaluator").count} length"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%PatternMatchEvaluator").count} pattern match"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%ExactMatchEvaluator").count} exact match"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%FormatEvaluator").count} format"
puts "    - #{PromptTracker::Evaluation.where("evaluator_type LIKE ?", "%ConversationJudgeEvaluator").count} conversation judge"
puts "  - #{PromptTracker::AbTest.count} A/B tests"
puts "    - #{PromptTracker::AbTest.draft.count} draft"
puts "    - #{PromptTracker::AbTest.running.count} running"
puts "    - #{PromptTracker::AbTest.completed.count} completed"

puts "\nTotal cost: $#{PromptTracker::LlmResponse.sum(:cost_usd).round(4)}"
puts "Average response time: #{PromptTracker::LlmResponse.successful.average(:response_time_ms).to_i}ms"

puts "\n🎉 Ready to explore!"
puts "\n💡 Tips:"
puts "  - Visit /prompt_tracker to see all prompts"
puts "  - View tests for customer_support_greeting v3"
puts "  - Advanced tests include:"
puts "    • Comprehensive Quality Check (3 evaluators: length, keyword, LLM judge)"
puts "    • Email Summary Format Validation (complex regex patterns)"
puts "    • Code Review Quality Assessment (LLM judge + keyword validation)"
puts "    • Exact Output Validation (exact match + quality checks)"
puts "    • Technical Content Pattern Validation (10 complex regex patterns + 4 evaluators)"
puts "  - Create new A/B tests with draft versions"
